name: 🚀 Publish Package

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🎉 Install pnpm
        uses: pnpm/action-setup@v4
      - name: 🎉 Set node version to lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - name: 🚧 Install deps
        run: pnpm install
      - name: 📦 Build
        run: pnpm run build
      - name: 🔀 Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
